version: "3.9"
# ref: https://docs.docker.com/compose/compose-file
services:
  app:
    image: book_line
    build:
      args:
        - target=dev
    volumes:
      - .:/app
    ports:
      - "18000:8080"
