version: "3.9"
# ref: https://docs.docker.com/compose/compose-file
# services:
#   app:
#     image: book_line
#     build:
#       args:
#         - target=dev
#     volumes:
#       - .:/app
#     ports:
#       - "18000:8080"
services:
  book_line_db:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: book_line_db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: book_line
      MYSQL_PASSWORD: book_line
      MYSQL_DATABASE: book_line
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - "33306:3306"